# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.rule_engine_controller_api import RuleEngineControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestRuleEngineControllerApi(unittest.TestCase):
    """RuleEngineControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.rule_engine_controller_api.RuleEngineControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_rule_engine_request_using_post(self):
        """Test case for handle_rule_engine_request_using_post

        handleRuleEngineRequest  # noqa: E501
        """
        pass

    def test_handle_rule_engine_request_using_post1(self):
        """Test case for handle_rule_engine_request_using_post1

        handleRuleEngineRequest  # noqa: E501
        """
        pass

    def test_handle_rule_engine_request_using_post2(self):
        """Test case for handle_rule_engine_request_using_post2

        handleRuleEngineRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
