# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from models.component_descriptor import ComponentDescriptor  # noqa: E501
from pyTB.rest import ApiException


class TestComponentDescriptor(unittest.TestCase):
    """ComponentDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentDescriptor(self):
        """Test ComponentDescriptor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyTB.models.component_descriptor.ComponentDescriptor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
