# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.custom_translation_controller_api import CustomTranslationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestCustomTranslationControllerApi(unittest.TestCase):
    """CustomTranslationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.custom_translation_controller_api.CustomTranslationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_custom_translation_using_get(self):
        """Test case for get_current_custom_translation_using_get

        getCurrentCustomTranslation  # noqa: E501
        """
        pass

    def test_get_custom_translation_using_get(self):
        """Test case for get_custom_translation_using_get

        getCustomTranslation  # noqa: E501
        """
        pass

    def test_save_custom_translation_using_post(self):
        """Test case for save_custom_translation_using_post

        saveCustomTranslation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
