# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.thing_park_integration_controller_api import ThingParkIntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestThingParkIntegrationControllerApi(unittest.TestCase):
    """ThingParkIntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.thing_park_integration_controller_api.ThingParkIntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_request_tpe_using_delete(self):
        """Test case for process_request_tpe_using_delete

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_get(self):
        """Test case for process_request_tpe_using_get

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_head(self):
        """Test case for process_request_tpe_using_head

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_options(self):
        """Test case for process_request_tpe_using_options

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_patch(self):
        """Test case for process_request_tpe_using_patch

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_post(self):
        """Test case for process_request_tpe_using_post

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_tpe_using_put(self):
        """Test case for process_request_tpe_using_put

        processRequestTPE  # noqa: E501
        """
        pass

    def test_process_request_using_delete3(self):
        """Test case for process_request_using_delete3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_get3(self):
        """Test case for process_request_using_get3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_head3(self):
        """Test case for process_request_using_head3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_options3(self):
        """Test case for process_request_using_options3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_patch3(self):
        """Test case for process_request_using_patch3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_post5(self):
        """Test case for process_request_using_post5

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_put3(self):
        """Test case for process_request_using_put3

        processRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
