# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.integration_controller_api import IntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestIntegrationControllerApi(unittest.TestCase):
    """IntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.integration_controller_api.IntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_integration_using_delete(self):
        """Test case for delete_integration_using_delete

        deleteIntegration  # noqa: E501
        """
        pass

    def test_get_integration_by_id_using_get(self):
        """Test case for get_integration_by_id_using_get

        getIntegrationById  # noqa: E501
        """
        pass

    def test_get_integration_by_routing_key_using_get(self):
        """Test case for get_integration_by_routing_key_using_get

        getIntegrationByRoutingKey  # noqa: E501
        """
        pass

    def test_get_integrations_by_ids_using_get(self):
        """Test case for get_integrations_by_ids_using_get

        getIntegrationsByIds  # noqa: E501
        """
        pass

    def test_get_integrations_using_get(self):
        """Test case for get_integrations_using_get

        getIntegrations  # noqa: E501
        """
        pass

    def test_save_integration_using_post(self):
        """Test case for save_integration_using_post

        saveIntegration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
