# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.role_controller_api import RoleControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestRoleControllerApi(unittest.TestCase):
    """RoleControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.role_controller_api.RoleControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_role_using_delete(self):
        """Test case for delete_role_using_delete

        deleteRole  # noqa: E501
        """
        pass

    def test_get_role_by_id_using_get(self):
        """Test case for get_role_by_id_using_get

        getRoleById  # noqa: E501
        """
        pass

    def test_get_roles_by_ids_using_get(self):
        """Test case for get_roles_by_ids_using_get

        getRolesByIds  # noqa: E501
        """
        pass

    def test_get_roles_using_get(self):
        """Test case for get_roles_using_get

        getRoles  # noqa: E501
        """
        pass

    def test_save_role_using_post(self):
        """Test case for save_role_using_post

        saveRole  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
