# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.http_integration_controller_api import HttpIntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestHttpIntegrationControllerApi(unittest.TestCase):
    """HttpIntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.http_integration_controller_api.HttpIntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_status_using_get(self):
        """Test case for check_status_using_get

        checkStatus  # noqa: E501
        """
        pass

    def test_process_request_using_post(self):
        """Test case for process_request_using_post

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_post1(self):
        """Test case for process_request_using_post1

        processRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
