# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.group_permission_controller_api import GroupPermissionControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestGroupPermissionControllerApi(unittest.TestCase):
    """GroupPermissionControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.group_permission_controller_api.GroupPermissionControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_group_permission_using_delete(self):
        """Test case for delete_group_permission_using_delete

        deleteGroupPermission  # noqa: E501
        """
        pass

    def test_get_entity_group_permissions_using_get(self):
        """Test case for get_entity_group_permissions_using_get

        getEntityGroupPermissions  # noqa: E501
        """
        pass

    def test_get_group_permission_by_id_using_get(self):
        """Test case for get_group_permission_by_id_using_get

        getGroupPermissionById  # noqa: E501
        """
        pass

    def test_get_user_group_permissions_using_get(self):
        """Test case for get_user_group_permissions_using_get

        getUserGroupPermissions  # noqa: E501
        """
        pass

    def test_save_group_permission_using_post(self):
        """Test case for save_group_permission_using_post

        saveGroupPermission  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
