# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.white_labeling_controller_api import WhiteLabelingControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestWhiteLabelingControllerApi(unittest.TestCase):
    """WhiteLabelingControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.white_labeling_controller_api.WhiteLabelingControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_login_white_label_params_using_get(self):
        """Test case for get_current_login_white_label_params_using_get

        getCurrentLoginWhiteLabelParams  # noqa: E501
        """
        pass

    def test_get_current_white_label_params_using_get(self):
        """Test case for get_current_white_label_params_using_get

        getCurrentWhiteLabelParams  # noqa: E501
        """
        pass

    def test_get_login_white_label_params_using_get(self):
        """Test case for get_login_white_label_params_using_get

        getLoginWhiteLabelParams  # noqa: E501
        """
        pass

    def test_get_white_label_params_using_get(self):
        """Test case for get_white_label_params_using_get

        getWhiteLabelParams  # noqa: E501
        """
        pass

    def test_is_customer_white_labeling_allowed_using_get(self):
        """Test case for is_customer_white_labeling_allowed_using_get

        isCustomerWhiteLabelingAllowed  # noqa: E501
        """
        pass

    def test_is_white_labeling_allowed_using_get(self):
        """Test case for is_white_labeling_allowed_using_get

        isWhiteLabelingAllowed  # noqa: E501
        """
        pass

    def test_preview_white_label_params_using_post(self):
        """Test case for preview_white_label_params_using_post

        previewWhiteLabelParams  # noqa: E501
        """
        pass

    def test_save_login_white_label_params_using_post(self):
        """Test case for save_login_white_label_params_using_post

        saveLoginWhiteLabelParams  # noqa: E501
        """
        pass

    def test_save_white_label_params_using_post(self):
        """Test case for save_white_label_params_using_post

        saveWhiteLabelParams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
