# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.entity_group_controller_api import EntityGroupControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestEntityGroupControllerApi(unittest.TestCase):
    """EntityGroupControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.entity_group_controller_api.EntityGroupControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_entities_to_entity_group_using_post(self):
        """Test case for add_entities_to_entity_group_using_post

        addEntitiesToEntityGroup  # noqa: E501
        """
        pass

    def test_delete_entity_group_using_delete(self):
        """Test case for delete_entity_group_using_delete

        deleteEntityGroup  # noqa: E501
        """
        pass

    def test_get_enitity_group_by_owner_and_name_and_type_using_get(self):
        """Test case for get_enitity_group_by_owner_and_name_and_type_using_get

        getEnitityGroupByOwnerAndNameAndType  # noqa: E501
        """
        pass

    def test_get_entities_using_get(self):
        """Test case for get_entities_using_get

        getEntities  # noqa: E501
        """
        pass

    def test_get_entity_group_all_by_owner_and_type_using_get(self):
        """Test case for get_entity_group_all_by_owner_and_type_using_get

        getEntityGroupAllByOwnerAndType  # noqa: E501
        """
        pass

    def test_get_entity_group_by_id_using_get(self):
        """Test case for get_entity_group_by_id_using_get

        getEntityGroupById  # noqa: E501
        """
        pass

    def test_get_entity_groups_by_ids_using_get(self):
        """Test case for get_entity_groups_by_ids_using_get

        getEntityGroupsByIds  # noqa: E501
        """
        pass

    def test_get_entity_groups_by_owner_and_type_using_get(self):
        """Test case for get_entity_groups_by_owner_and_type_using_get

        getEntityGroupsByOwnerAndType  # noqa: E501
        """
        pass

    def test_get_entity_groups_by_type_using_get(self):
        """Test case for get_entity_groups_by_type_using_get

        getEntityGroupsByType  # noqa: E501
        """
        pass

    def test_get_entity_groups_for_entity_using_get(self):
        """Test case for get_entity_groups_for_entity_using_get

        getEntityGroupsForEntity  # noqa: E501
        """
        pass

    def test_get_group_entity_using_get(self):
        """Test case for get_group_entity_using_get

        getGroupEntity  # noqa: E501
        """
        pass

    def test_get_owners_using_get(self):
        """Test case for get_owners_using_get

        getOwners  # noqa: E501
        """
        pass

    def test_make_entity_group_private_using_post(self):
        """Test case for make_entity_group_private_using_post

        makeEntityGroupPrivate  # noqa: E501
        """
        pass

    def test_make_entity_group_public_using_post(self):
        """Test case for make_entity_group_public_using_post

        makeEntityGroupPublic  # noqa: E501
        """
        pass

    def test_remove_entities_from_entity_group_using_post(self):
        """Test case for remove_entities_from_entity_group_using_post

        removeEntitiesFromEntityGroup  # noqa: E501
        """
        pass

    def test_save_entity_group_using_post(self):
        """Test case for save_entity_group_using_post

        saveEntityGroup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
