# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.owner_controller_api import OwnerControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestOwnerControllerApi(unittest.TestCase):
    """OwnerControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.owner_controller_api.OwnerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_owner_to_customer_using_post(self):
        """Test case for change_owner_to_customer_using_post

        changeOwnerToCustomer  # noqa: E501
        """
        pass

    def test_change_owner_to_tenant_using_post(self):
        """Test case for change_owner_to_tenant_using_post

        changeOwnerToTenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
