# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.sign_up_controller_api import SignUpControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestSignUpControllerApi(unittest.TestCase):
    """SignUpControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.sign_up_controller_api.SignUpControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_privacy_policy_using_post(self):
        """Test case for accept_privacy_policy_using_post

        acceptPrivacyPolicy  # noqa: E501
        """
        pass

    def test_activate_email_using_get(self):
        """Test case for activate_email_using_get

        activateEmail  # noqa: E501
        """
        pass

    def test_activate_user_by_email_code_using_post(self):
        """Test case for activate_user_by_email_code_using_post

        activateUserByEmailCode  # noqa: E501
        """
        pass

    def test_privacy_policy_accepted_using_get(self):
        """Test case for privacy_policy_accepted_using_get

        privacyPolicyAccepted  # noqa: E501
        """
        pass

    def test_resend_email_activation_using_post(self):
        """Test case for resend_email_activation_using_post

        resendEmailActivation  # noqa: E501
        """
        pass

    def test_sign_up_using_post(self):
        """Test case for sign_up_using_post

        signUp  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
