# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.ocean_connect_integration_controller_api import OceanConnectIntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestOceanConnectIntegrationControllerApi(unittest.TestCase):
    """OceanConnectIntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.ocean_connect_integration_controller_api.OceanConnectIntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_request_using_delete(self):
        """Test case for process_request_using_delete

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_get(self):
        """Test case for process_request_using_get

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_head(self):
        """Test case for process_request_using_head

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_options(self):
        """Test case for process_request_using_options

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_patch(self):
        """Test case for process_request_using_patch

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_post2(self):
        """Test case for process_request_using_post2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_put(self):
        """Test case for process_request_using_put

        processRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
