# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.user_controller_api import UserControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.user_controller_api.UserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user_using_delete(self):
        """Test case for delete_user_using_delete

        deleteUser  # noqa: E501
        """
        pass

    def test_get_activation_link_using_get(self):
        """Test case for get_activation_link_using_get

        getActivationLink  # noqa: E501
        """
        pass

    def test_get_all_customer_users_using_get(self):
        """Test case for get_all_customer_users_using_get

        getAllCustomerUsers  # noqa: E501
        """
        pass

    def test_get_customer_users_using_get(self):
        """Test case for get_customer_users_using_get

        getCustomerUsers  # noqa: E501
        """
        pass

    def test_get_tenant_admins_using_get(self):
        """Test case for get_tenant_admins_using_get

        getTenantAdmins  # noqa: E501
        """
        pass

    def test_get_user_by_id_using_get(self):
        """Test case for get_user_by_id_using_get

        getUserById  # noqa: E501
        """
        pass

    def test_get_user_token_using_get(self):
        """Test case for get_user_token_using_get

        getUserToken  # noqa: E501
        """
        pass

    def test_get_user_users_using_get(self):
        """Test case for get_user_users_using_get

        getUserUsers  # noqa: E501
        """
        pass

    def test_get_users_by_entity_group_id_using_get(self):
        """Test case for get_users_by_entity_group_id_using_get

        getUsersByEntityGroupId  # noqa: E501
        """
        pass

    def test_get_users_by_ids_using_get(self):
        """Test case for get_users_by_ids_using_get

        getUsersByIds  # noqa: E501
        """
        pass

    def test_is_user_token_access_enabled_using_get(self):
        """Test case for is_user_token_access_enabled_using_get

        isUserTokenAccessEnabled  # noqa: E501
        """
        pass

    def test_save_user_using_post(self):
        """Test case for save_user_using_post

        saveUser  # noqa: E501
        """
        pass

    def test_send_activation_email_using_post(self):
        """Test case for send_activation_email_using_post

        sendActivationEmail  # noqa: E501
        """
        pass

    def test_set_user_credentials_enabled_using_post(self):
        """Test case for set_user_credentials_enabled_using_post

        setUserCredentialsEnabled  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
