# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.converter_controller_api import ConverterControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestConverterControllerApi(unittest.TestCase):
    """ConverterControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.converter_controller_api.ConverterControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_converter_using_delete(self):
        """Test case for delete_converter_using_delete

        deleteConverter  # noqa: E501
        """
        pass

    def test_get_converter_by_id_using_get(self):
        """Test case for get_converter_by_id_using_get

        getConverterById  # noqa: E501
        """
        pass

    def test_get_converters_by_ids_using_get(self):
        """Test case for get_converters_by_ids_using_get

        getConvertersByIds  # noqa: E501
        """
        pass

    def test_get_converters_using_get(self):
        """Test case for get_converters_using_get

        getConverters  # noqa: E501
        """
        pass

    def test_get_latest_converter_debug_input_using_get(self):
        """Test case for get_latest_converter_debug_input_using_get

        getLatestConverterDebugInput  # noqa: E501
        """
        pass

    def test_save_converter_using_post(self):
        """Test case for save_converter_using_post

        saveConverter  # noqa: E501
        """
        pass

    def test_test_down_link_converter_using_post(self):
        """Test case for test_down_link_converter_using_post

        testDownLinkConverter  # noqa: E501
        """
        pass

    def test_test_up_link_converter_using_post(self):
        """Test case for test_up_link_converter_using_post

        testUpLinkConverter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
