# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.blob_entity_controller_api import BlobEntityControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestBlobEntityControllerApi(unittest.TestCase):
    """BlobEntityControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.blob_entity_controller_api.BlobEntityControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_blob_entity_using_delete(self):
        """Test case for delete_blob_entity_using_delete

        deleteBlobEntity  # noqa: E501
        """
        pass

    def test_download_blob_entity_using_get(self):
        """Test case for download_blob_entity_using_get

        downloadBlobEntity  # noqa: E501
        """
        pass

    def test_get_blob_entities_by_ids_using_get(self):
        """Test case for get_blob_entities_by_ids_using_get

        getBlobEntitiesByIds  # noqa: E501
        """
        pass

    def test_get_blob_entities_using_get(self):
        """Test case for get_blob_entities_using_get

        getBlobEntities  # noqa: E501
        """
        pass

    def test_get_blob_entity_info_by_id_using_get(self):
        """Test case for get_blob_entity_info_by_id_using_get

        getBlobEntityInfoById  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
