# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.custom_menu_controller_api import CustomMenuControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestCustomMenuControllerApi(unittest.TestCase):
    """CustomMenuControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.custom_menu_controller_api.CustomMenuControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_custom_menu_using_get(self):
        """Test case for get_current_custom_menu_using_get

        getCurrentCustomMenu  # noqa: E501
        """
        pass

    def test_get_custom_menu_using_get(self):
        """Test case for get_custom_menu_using_get

        getCustomMenu  # noqa: E501
        """
        pass

    def test_save_custom_menu_using_post(self):
        """Test case for save_custom_menu_using_post

        saveCustomMenu  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
