# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.self_registration_controller_api import SelfRegistrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestSelfRegistrationControllerApi(unittest.TestCase):
    """SelfRegistrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.self_registration_controller_api.SelfRegistrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_privacy_policy_using_get(self):
        """Test case for get_privacy_policy_using_get

        getPrivacyPolicy  # noqa: E501
        """
        pass

    def test_get_self_registration_params_using_get(self):
        """Test case for get_self_registration_params_using_get

        getSelfRegistrationParams  # noqa: E501
        """
        pass

    def test_get_sign_up_self_registration_params_using_get(self):
        """Test case for get_sign_up_self_registration_params_using_get

        getSignUpSelfRegistrationParams  # noqa: E501
        """
        pass

    def test_save_self_registration_params_using_post(self):
        """Test case for save_self_registration_params_using_post

        saveSelfRegistrationParams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
