# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.sig_fox_integration_controller_api import SigFoxIntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestSigFoxIntegrationControllerApi(unittest.TestCase):
    """SigFoxIntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.sig_fox_integration_controller_api.SigFoxIntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_request_using_delete1(self):
        """Test case for process_request_using_delete1

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_get1(self):
        """Test case for process_request_using_get1

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_head1(self):
        """Test case for process_request_using_head1

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_options1(self):
        """Test case for process_request_using_options1

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_patch1(self):
        """Test case for process_request_using_patch1

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_post3(self):
        """Test case for process_request_using_post3

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_put1(self):
        """Test case for process_request_using_put1

        processRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
