# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.report_controller_api import ReportControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestReportControllerApi(unittest.TestCase):
    """ReportControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.report_controller_api.ReportControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_dashboard_report_using_post(self):
        """Test case for download_dashboard_report_using_post

        downloadDashboardReport  # noqa: E501
        """
        pass

    def test_download_test_report_using_post(self):
        """Test case for download_test_report_using_post

        downloadTestReport  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
