# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.user_permissions_controller_api import UserPermissionsControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestUserPermissionsControllerApi(unittest.TestCase):
    """UserPermissionsControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.user_permissions_controller_api.UserPermissionsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_allowed_permissions_using_get(self):
        """Test case for get_allowed_permissions_using_get

        getAllowedPermissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
