# coding: utf-8

"""
    Thingsboard REST API

    For instructions how to authorize requests please visit <a href='http://thingsboard.io/docs/reference/rest-api/'>REST API documentation page</a>.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: info@thingsboard.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyTB
from api.t_mobile_iot_cdp_integration_controller_api import TMobileIotCdpIntegrationControllerApi  # noqa: E501
from pyTB.rest import ApiException


class TestTMobileIotCdpIntegrationControllerApi(unittest.TestCase):
    """TMobileIotCdpIntegrationControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.t_mobile_iot_cdp_integration_controller_api.TMobileIotCdpIntegrationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_request_using_delete2(self):
        """Test case for process_request_using_delete2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_get2(self):
        """Test case for process_request_using_get2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_head2(self):
        """Test case for process_request_using_head2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_options2(self):
        """Test case for process_request_using_options2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_patch2(self):
        """Test case for process_request_using_patch2

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_post4(self):
        """Test case for process_request_using_post4

        processRequest  # noqa: E501
        """
        pass

    def test_process_request_using_put2(self):
        """Test case for process_request_using_put2

        processRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
